import { FileText, CheckCircle2, Shield, Info } from "lucide-react";

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Title */}
      <div className="bg-white p-6 rounded-sm border border-slate-300 shadow-sm space-y-2">
        <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase text-[#0f2942]">
          <FileText className="h-4 w-4" />
          Technical Documentation
        </div>
        <h1 className="text-2xl sm:text-3xl font-black text-[#0f2942]">Measurement Methodology</h1>
        <p className="text-xs text-slate-600">
          Formal technical specification explaining how network performance metrics are sampled, measured, and calculated by NetPulse.
        </p>
      </div>

      {/* Main Document Body */}
      <div className="bg-white p-6 sm:p-8 rounded-sm border border-slate-300 shadow-sm space-y-8 text-xs text-slate-700 leading-relaxed font-sans">
        {/* Section 1 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            1. Overview
          </h2>
          <p>
            NetPulse measures network performance using controlled binary data transfers between the user's web browser and configured measurement endpoints. All measurements are executed over standard HTTPS protocols using native browser APIs (`fetch`, `ReadableStream`, `XMLHttpRequest`) to ensure reliable end-to-end telemetry.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            2. Test Server Selection
          </h2>
          <p>
            Prior to testing, NetPulse sends initial micro-requests to available measurement edge servers. The server responding with the lowest round-trip latency is automatically designated as the active endpoint for subsequent latency, download, and upload tests.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            3. Latency Measurement
          </h2>
          <p>
            Latency (ping) represents the round-trip time (RTT) required for a small packet to travel from the browser to the measurement server and back. NetPulse executes N sequential HTTP requests (default: 8 requests) with unique cache-busting timestamps. The initial request is excluded to compensate for TCP handshake overhead, and the arithmetic mean of remaining valid samples is computed in milliseconds.
          </p>
        </section>

        {/* Section 4 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            4. Jitter Calculation
          </h2>
          <p>
            Jitter measures the stability and variance of latency over time. NetPulse calculates jitter as the mean absolute difference between consecutive latency samples:
          </p>

          <div className="p-3 bg-slate-50 border border-slate-300 font-mono text-[11px] text-slate-800 rounded-sm">
            Jitter = (1 / (N - 1)) * ∑ | Latency(i) - Latency(i - 1) |
          </div>

          <p>Lower jitter values (below 3 ms) indicate a consistent connection suitable for real-time applications.</p>
        </section>

        {/* Section 5 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            5. Download Measurement
          </h2>
          <p>
            Download speed is evaluated by requesting binary byte streams from the measurement endpoint across concurrent connections. Instantaneous throughput is sampled every 150 milliseconds. To eliminate initial TCP ramp-up bias, early samples (first 1.5 seconds) are excluded, and final Mbps is computed from stable sample intervals.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            6. Upload Measurement
          </h2>
          <p>
            Upload speed is calculated by transmitting generated byte array payloads to the measurement server. NetPulse monitors exact transferred byte counts using `XMLHttpRequest.upload.onprogress` callbacks. Transferred payloads are discarded immediately by the server upon receipt.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            7. Connection Quality Index
          </h2>
          <p>
            NetPulse connection quality scores (0 to 100) are assigned using a weighted mathematical index balancing download bandwidth (40%), upload bandwidth (25%), latency (20%), and jitter (15%). Score ratings are grouped into:
          </p>
          <ul className="list-disc list-inside space-y-1 font-mono text-[11px] text-slate-800">
            <li><strong>80–100: EXCELLENT</strong> (Suitable for 4K streaming & low-latency applications)</li>
            <li><strong>60–79: GOOD</strong> (Suitable for HD streaming & remote collaboration)</li>
            <li><strong>40–59: FAIR</strong> (Suitable for standard definition browsing)</li>
            <li><strong>0–39: POOR</strong> (Basic text messaging & light web access)</li>
          </ul>
        </section>

        {/* Section 8 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            8. Measurement Limitations
          </h2>
          <p>
            Measurements are performed in the user's web browser environment and may be affected by Wi-Fi interference, background device processing, browser tab resource caps, and local network congestion. They are provided as estimates and do not constitute legal guarantees of ISP service agreements.
          </p>
        </section>

        {/* Section 9 */}
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#0f2942] border-b border-slate-200 pb-2">
            9. Data Handling & Security
          </h2>
          <p>
            NetPulse does not permanently store test payloads or personal identifier data. Test metrics saved to history are associated either locally within browser storage or tied securely to authenticated user accounts via Row Level Security (RLS).
          </p>
        </section>
      </div>
    </div>
  );
}
